# Generated by Django 4.2.7 on 2023-11-30 01:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import froala_editor.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("token", models.CharField(max_length=100)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NewsModel",
            fields=[
                ("title", models.CharField(max_length=1000)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("content", froala_editor.fields.FroalaField()),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=1000, null=True, unique=True
                    ),
                ),
                ("views", models.IntegerField(default=0)),
                ("image", models.ImageField(upload_to="blog")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("upload_to", models.DateTimeField(auto_now=True)),
                ("tags", models.CharField(default="News", max_length=1000)),
                ("summary", models.CharField(default="Just a News", max_length=10000)),
                ("source_url", models.CharField(default="No Source", max_length=1000)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.category"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
