# Generated by Django 4.1.10 on 2023-10-25 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='category',
            field=models.CharField(default='News', max_length=1000),
        ),
    ]
