# Generated by Django 4.1.10 on 2023-10-26 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_category_blogmodel_tags_alter_blogmodel_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='source_url',
            field=models.CharField(default='No Source', max_length=1000),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='summary',
            field=models.CharField(default='Just a News', max_length=10000),
        ),
    ]
